fix(Sonar scan):Adjust sonar workflow

diff --git a/.github/workflows/develop-pr-ci.yml b/.github/workflows/develop-pr-ci.yml
--- a/.github/workflows/develop-pr-ci.yml
+++ b/.github/workflows/develop-pr-ci.yml
@@ -16,24 +16,20 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
       - name: Setup JDK
         uses: actions/setup-java@v3
         with:
           java-version: "17"
           distribution: temurin
-      - name: Setup environment variables
-        run: >
-          echo "SONAR_CLOUD_TOKEN=${{ secrets.SONAR_CLOUD_TOKEN }}" >> $GITHUB_ENV
 
-          echo "MY_VARIABLE_2=${{ secrets.MY_VARIABLE_2 }}" >> $GITHUB_ENV
-
-          echo "MY_VARIABLE_3=${{ secrets.MY_VARIABLE_3 }}" >> $GITHUB_ENV
       - name: Create .env file
         run: |
           echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
           echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
           echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
           echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
+
       - name: Cache Maven dependencies
         uses: actions/cache@v3
         with:
@@ -41,17 +37,28 @@ jobs:
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven
+
       - name: Build application
         run: mvn clean install -DskipTests
+
       - name: Run tests and generate JaCoCo report
         run: mvn clean verify
-      - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@v2
+
+      - name: Build and analyze
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
+        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TAndrian_we-go-jim
+
+      - name: Check Quality Gate status
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
-        with:
-          args: >
-            -Dsonar.projectKey=${{ github.repository_variables.SONAR_PROJECT_KEY }}"
-            -Dsonar.organization=your-${{github.repository_variables.SONAR_ORGANIZATION }}"
-            -Dsonar.host.url=${{ github.repository_variables.SONAR_HOST }}"
-            -Dsonar.qualitygate.wait=true
+        run: |
+          STATUS=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=TAndrian_we-go-jim" -u $SONAR_TOKEN:)
+          echo "Quality Gate status: $STATUS"
+          if [[ "$STATUS" != *"\"status\":\"OK\""* ]]; then
+            echo "Quality Gate failed"
+            exit 1
+          else
+            echo "Quality Gate passed"
+          fi
